server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: SAMPLE-SERVICE
          uri: lb://SAMPLE-SERVICE
          predicates:a                          q` `1 
            - Path=/api/sample/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost